INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (0, '28', '0', '0', Precious, 'Achiuwa', '1999-09-19', 'Nigeria', '6-8');
INSERT INTO player_contract (id_contract, money, length VALUES (0, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '0', '2023-24', '4379527');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (1, 'None', '1', '1', Steven, 'Adams', '1993-07-20', 'New Zealand', '6-11');
INSERT INTO player_contract (id_contract, money, length VALUES (1, 'extension', 'extension');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '1', '2023-24', '12600000');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '1', '2024-25', '12600000');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (2, '16', '2', '2', Bam, 'Adebayo', '1997-07-18', 'New Jersey USA', '6-9');
INSERT INTO player_contract (id_contract, money, length VALUES (2, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '2', '2023-24', '32600060');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '2', '2024-25', '34848340');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (3, '2', '2025-26', '37096620');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (3, '29', '3', '3', Ochai, 'Agbaji', '2000-04-20', 'Wisconsin USA', '6-5');
INSERT INTO player_contract (id_contract, money, length VALUES (3, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '3', '2023-24', '4114200');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '3', '2024-25', '4310280');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (3, '3', '2025-26', '6383525');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (4, '15', '4', '4', Santi, 'Aldama', '2001-01-10', 'Spain', '6-11');
INSERT INTO player_contract (id_contract, money, length VALUES (4, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '4', '2023-24', '2194200');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '4', '2024-25', '3960531');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (5, 'None', '5', '5', Ty-Shon, 'Alexander', '1998-07-16', 'North Carolina USA', '6-3');
INSERT INTO player_contract (id_contract, money, length VALUES (5, 'None', 'None');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (6, '18', '6', '6', Nickeil, 'Alexander-Walker', '1998-09-02', 'Canada', '6-5');
INSERT INTO player_contract (id_contract, money, length VALUES (6, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '6', '2023-24', '4687500');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '6', '2024-25', '4312500');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (7, 'None', '7', '7', Rawle, 'Alkins', '1997-10-29', 'New York USA', '6-5');
INSERT INTO player_contract (id_contract, money, length VALUES (7, 'None', 'None');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (8, '24', '8', '8', Grayson, 'Allen', '1995-10-08', 'Florida USA', '6-4');
INSERT INTO player_contract (id_contract, money, length VALUES (8, '18.7', '2');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '8', '2023-24', '8925000');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (9, '6', '9', '9', Jarrett, 'Allen', '1998-04-21', 'California USA', '6-11');
INSERT INTO player_contract (id_contract, money, length VALUES (9, 'rookie', 'rookie');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '9', '2023-24', '20000000');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '9', '2024-25', '20000000');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (3, '9', '2025-26', '20000000');
INSERT INTO player (id_player, id_team, id_contract, id_player_stats, name, surname, date_of_birth, nationality, height) VALUES (10, '19', '10', '10', Jose, 'Alvarado', '1998-04-12', 'New York USA', '6-0');
INSERT INTO player_contract (id_contract, money, length VALUES (10, 'two-way', 'two-way');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (1, '10', '2023-24', '1836096');
INSERT INTO contract_year (id_contract_year, id_contract, year, money) VALUES (2, '10', '2024-25', '1988598');
